### ISSUE TITLE
iCubGazeboV2_5 unstable if it is controlled using velocity mode 

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models#13]
When I try to switch from `position` control to `velocity` control iCub jumps and the switched joint goes in `hardware fault`.
Here a simple example.

![velocityMode_old](https://user-images.githubusercontent.com/16744101/39699914-8e61b9c4-51fb-11e8-9904-ca760093b5a0.gif)

I have tried to tune the PID controller of the l_shoulder_pitch` joint:

| Gain | Old   |  New |
|:----:|-------|:----:|
|  Kp  | 8.726 | 0.85 |
|  Kd  | 0.035 |   0  |
|  Ki  | 0.002 |  0.15 |

This is the result 

![velocityMode_new](https://user-images.githubusercontent.com/16744101/39700595-07f3ca5a-51fe-11e8-9744-1c3868d2b924.gif)

**Comment by traversaro** [comment]
Great @GiulioRomualdi . You can open a PR against the configuration file that are stored in icub-model-generator, see : https://github.com/robotology-playground/icub-model-generator/tree/master/simmechanics/data/icub2_5/conf .

**Comment by fiorisi** [comment]
With @gabrielenava we noticed that in the new `gif` the arm of the robot is slowly moving down. this is probably due to the fact that the Kp gain is low. Did you try to reduce the time step of the Gazebo simulation with the [`Old`](https://github.com/robotology-playground/icub-models/issues/13#issue-320776453) gains?

**Comment by GiulioRomualdi** [comment]
@fiorisi I have just tried. The results is the same of before: the switched joint goes in hardware fault.

**Comment by traversaro** [comment]
With PR https://github.com/robotology/icub-models-generator/pull/138, we switched the velocity control mode to actually send a velocity to a low-level integrator, whose output is then send to the usual position control. For this reason, I think that this issue is now solved, and it can be closed. Feel free to reopen if a similar error is still present.
