### ISSUE TITLE
Weight and drawing of hand

### ISSUE THREAD

**Issue by KhomutovEvgeniy** [robotology/icub-models#34]
What is the weight of hand iCub?
I tried to find dimensions of hand like finger phalanx length in assembly drawing and found out that to open assembly files need PTC Creo commercial version. I have only student version. 

Could you send a link for drawing of hand compatible with student version to meashure finger sizes and their position?

**Comment by traversaro** [comment]
Hi @KhomutovEvgeniy, sorry for the delayed response, I did not noticed this issue back in time. You were able to satisfy your question by other means?

**Comment by KhomutovEvgeniy** [comment]
Hi @traversaro, I solved the issue with the drawing of hand, but I could'n find information about weight of forearm and hand, I found information only about mass of the whole arm.

**Comment by traversaro** [comment]
The nominal weight of the hand and the forrearm for the iCub 2.5 model is available in the URDF:
* `l_hand` link (from https://github.com/robotology/icub-models/blob/v1.17.0/iCub/robots/iCubGazeboV2_5/model.urdf#L2050):  0.247806 Kg 
* `l_forearm` link (from https://github.com/robotology/icub-models/blob/v1.17.0/iCub/robots/iCubGazeboV2_5/model.urdf#L1815): 0.636185 Kg. 

Note that the actual value could differ from those due to differences between the real object and the CAD model.

**Comment by traversaro** [comment]
@KhomutovEvgeniy  if this reply is ok for you, feel free to close the issue, thanks!
