### ISSUE TITLE
[iCubGazeboV2_5] Problem on the feet collisions

### ISSUE THREAD

**Issue by GiulioRomualdi** [robotology/icub-models#68]
I noticed that https://github.com/robotology/icub-models/commit/f95aa8759ed1d9bf8fb4b32d908b549573aa658c changes the collision of the feet. Now the original foot `sdl` is used instead of the rectangle. Consequentially gazebo has some problems while computing the contacts. 

![ezgif com-gif-maker (8)](https://user-images.githubusercontent.com/16744101/99649723-da1ec080-2a54-11eb-8a62-883cc0c6585d.gif)

I'm using gazebo 11 with ode

cc @Nicogene @traversaro (and some gazebo users @prashanthr05 @S-Dafarra)

**Comment by traversaro** [comment]
Thanks. My looking at the icub-model-generator commit, it is possible to see that this is a regression of https://github.com/robotology/icub-models-generator/commit/bd5033f1664009c9a89d23162d1b8b8462958454 , that is the commit after the merge of https://github.com/robotology/icub-models-generator/pull/165 .  I think the regression is due to these lines: https://github.com/robotology/icub-models-generator/pull/165/files#diff-8d60e60521ab05787f395488d975d4594b03d1b4fa1a83038fce9ca1935581b4R155
that set the `ASSIGNED_COLLISION_GEOMETRIES` variable to `""` if the iCub3-related options is not passed, so also in the case of iCub 2.* .
